# Load libraries
```{r}
.libPaths("/usr/lib/R/site-library")
library("edgeR", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("DESeq2", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("DEsingle", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("biomaRt",quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("goseq" ,quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("VennDiagram", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("ggpubr", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("Rtsne", quietly = TRUE,lib.loc="/usr/lib/R/site-library")
library("MEGENA",quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("DGCA", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library('dplyr', quietly = TRUE,lib.loc="/usr/lib/R/site-library")
library("ggplot2", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("ggrepel", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("gridExtra",quietly = TRUE , lib.loc="/usr/lib/R/site-library")
library("readr" , quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("ggfortify" , quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("cowplot" , quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("tidyverse", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("WGCNA", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("reshape2", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("foreach", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("doParallel", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("bigmemory", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("gtools", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("data.table", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("flashClust", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("dendextend", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library('vegan', quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("ade4", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("gridGraphics", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library("networkD3", quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library(readxl, quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library(dplyr, quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library(tidyr, quietly = TRUE, lib.loc="/usr/lib/R/site-library")
library(plotly, quietly = TRUE, lib.loc="/usr/lib/R/site-library")

```
# Run the RNA Seq R script first to be able to Load the annotation 
```{r}
annotation.ensembl.symbol <-read.table(file = "/home/yassine/Downloads/between_tissue/annotation.ensembl.symbol.txt",
                                       header= TRUE, 
                                       sep= "\t")

gene.length<-read.table(file = "/home/yassine/Downloads/between_tissue/gene.length.txt",
                                       header= TRUE, 
                                       sep= "\t")

annotation.GO.biomart<-read.table (file ="/home/yassine/Downloads/between_tissue/annotation.GO.biomart.txt",
                                       header= TRUE, 
                                       sep= "\t")
```


```{r}
count_data_b<-read.table (file ="/home/yassine/Downloads/count_data_b.txt",
                          header= TRUE,
                          sep= "\t")
rownames(count_data_b)<-count_data_annotated$Row.names
```

```{r}
columns_to_remove <- grepl("J148B_hypothalamus_6|H273B_hypothalamus_9", colnames(count_data_b))
count_data_b <- count_data_b[, !columns_to_remove]
```

```{r}
# Number of CPU cores to use
num_cores <- 4
# Register parallel cluster
cl <- makeCluster(num_cores)
registerDoParallel(cl)
```

```{r}
pwbc_columns_6 <- grep("pwbc_6", colnames(count_data_b))
count_data_pwbc_6 <- count_data_b[, pwbc_columns_6]
```

```{r}
count_data_pwbc_6$geneID <- rownames(count_data_pwbc_6)
```

```{r}
pwbc_6_count_data_annotated<-merge(count_data_pwbc_6,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_pwbc_6 <- count_data_pwbc_6[, -ncol(count_data_pwbc_6)]

pwbc_6_gene_length<-pwbc_6_count_data_annotated$transcript_length
```

```{r}
x <- count_data_pwbc_6 / pwbc_6_gene_length
pwbc_6_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
pwbc_6_fpkm<-as.data.frame(edgeR::rpkm(count_data_pwbc_6, pwbc_6_gene_length))
pwbc_6_cpm<-as.data.frame(edgeR::cpm(count_data_pwbc_6))
pwbc_6_cpm_filtered<-pwbc_6_cpm[rowSums(pwbc_6_cpm>1) > 9,]
pwbc_6_tpm_filtered<-pwbc_6_fpkm[rowSums(pwbc_6_tpm>1) > 9,]

genes_expressed_pwbc_6<-intersect(rownames(pwbc_6_cpm_filtered), rownames(pwbc_6_tpm_filtered))

pwbc_6_tpm_filtered<-pwbc_6_tpm_filtered[rownames(pwbc_6_tpm_filtered) %in% genes_expressed_pwbc_6,]
pwbc_6_cpm_filtered<-pwbc_6_cpm_filtered[rownames(pwbc_6_cpm_filtered) %in% genes_expressed_pwbc_6,]

pwbc_6_count_filtered<-count_data_pwbc_6[rownames(count_data_pwbc_6) %in% genes_expressed_pwbc_6,]

pwbc_6_tpm_filtered<-pwbc_6_tpm_filtered[complete.cases(pwbc_6_tpm_filtered),]
pwbc_6_count_filtered<-pwbc_6_count_filtered[complete.cases(pwbc_6_count_filtered),]

```

```{r}
write_delim(pwbc_6_count_filtered,
            "/home/yassine/Downloads/between_tissue/pwbc_6_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(pwbc_6_count_filtered)
norm_factors <- calcNormFactors(object = pwbc_6_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_pwbc_6 <- sweep(pwbc_6_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_pwbc_6<-asinh(CTF_normalized_pwbc_6)
```


```{r}
write_delim(asinh_transf_CTF_normalized_pwbc_6,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_pwbc_6.txt",
            delim = "\t",
            quote =  "none")
```



```{r}
pwbc_columns_9<- grep("pwbc_9", colnames(count_data_b))
count_data_pwbc_9<- count_data_b[, pwbc_columns_9]
```

```{r}
count_data_pwbc_9$geneID <- rownames(count_data_pwbc_9)
```

```{r}
pwbc_9_count_data_annotated<-merge(count_data_pwbc_9,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_pwbc_9<- count_data_pwbc_9[, -ncol(count_data_pwbc_9)]

pwbc_9_gene_length<-pwbc_9_count_data_annotated$transcript_length
```

```{r}
x <- count_data_pwbc_9/ pwbc_9_gene_length
pwbc_9_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
pwbc_9_fpkm<-as.data.frame(edgeR::rpkm(count_data_pwbc_9, pwbc_9_gene_length))
pwbc_9_cpm<-as.data.frame(edgeR::cpm(count_data_pwbc_9))
pwbc_9_cpm_filtered<-pwbc_9_cpm[rowSums(pwbc_9_cpm>1) > 9,]
pwbc_9_tpm_filtered<-pwbc_9_fpkm[rowSums(pwbc_9_tpm>1) > 9,]

genes_expressed_pwbc_9<-intersect(rownames(pwbc_9_cpm_filtered), rownames(pwbc_9_tpm_filtered))

pwbc_9_tpm_filtered<-pwbc_9_tpm_filtered[rownames(pwbc_9_tpm_filtered) %in% genes_expressed_pwbc_9,]
pwbc_9_cpm_filtered<-pwbc_9_cpm_filtered[rownames(pwbc_9_cpm_filtered) %in% genes_expressed_pwbc_9,]

pwbc_9_count_filtered<-count_data_pwbc_9[rownames(count_data_pwbc_9) %in% genes_expressed_pwbc_9,]

pwbc_9_tpm_filtered<-pwbc_9_tpm_filtered[complete.cases(pwbc_9_tpm_filtered),]
pwbc_9_count_filtered<-pwbc_9_count_filtered[complete.cases(pwbc_9_count_filtered),]

```

```{r}
write_delim(pwbc_9_count_filtered,
            "/home/yassine/Downloads/between_tissue/pwbc_9_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(pwbc_9_count_filtered)
norm_factors <- calcNormFactors(object = pwbc_9_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_pwbc_9 <- sweep(pwbc_9_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_pwbc_9<-asinh(CTF_normalized_pwbc_9)
```


```{r}
write_delim(asinh_transf_CTF_normalized_pwbc_9,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_pwbc_9.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
pwbc_columns_19<- grep("pwbc_19", colnames(count_data_b))
count_data_pwbc_19<- count_data_b[, pwbc_columns_19]
```

```{r}
count_data_pwbc_19$geneID <- rownames(count_data_pwbc_19)
```

```{r}
pwbc_19_count_data_annotated<-merge(count_data_pwbc_19,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_pwbc_19<- count_data_pwbc_19[, -ncol(count_data_pwbc_19)]

pwbc_19_gene_length<-pwbc_19_count_data_annotated$transcript_length
```

```{r}
x <- count_data_pwbc_19/ pwbc_19_gene_length
pwbc_19_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
pwbc_19_fpkm<-as.data.frame(edgeR::rpkm(count_data_pwbc_19, pwbc_19_gene_length))
pwbc_19_cpm<-as.data.frame(edgeR::cpm(count_data_pwbc_19))
pwbc_19_cpm_filtered<-pwbc_19_cpm[rowSums(pwbc_19_cpm>1) > 9,]
pwbc_19_tpm_filtered<-pwbc_19_fpkm[rowSums(pwbc_19_tpm>1) > 9,]

genes_expressed_pwbc_19<-intersect(rownames(pwbc_19_cpm_filtered), rownames(pwbc_19_tpm_filtered))

pwbc_19_tpm_filtered<-pwbc_19_tpm_filtered[rownames(pwbc_19_tpm_filtered) %in% genes_expressed_pwbc_19,]
pwbc_19_cpm_filtered<-pwbc_19_cpm_filtered[rownames(pwbc_19_cpm_filtered) %in% genes_expressed_pwbc_19,]

pwbc_19_count_filtered<-count_data_pwbc_19[rownames(count_data_pwbc_19) %in% genes_expressed_pwbc_19,]

pwbc_19_tpm_filtered<-pwbc_19_tpm_filtered[complete.cases(pwbc_19_tpm_filtered),]
pwbc_19_count_filtered<-pwbc_19_count_filtered[complete.cases(pwbc_19_count_filtered),]

```

```{r}
write_delim(pwbc_19_count_filtered,
            "/home/yassine/Downloads/between_tissue/pwbc_19_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(pwbc_19_count_filtered)
norm_factors <- calcNormFactors(object = pwbc_19_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_pwbc_19 <- sweep(pwbc_19_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_pwbc_19<-asinh(CTF_normalized_pwbc_19)
```


```{r}
write_delim(asinh_transf_CTF_normalized_pwbc_19,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_pwbc_19.txt",
            delim = "\t",
            quote =  "none")
```


#-------------

```{r}
endometrium_columns_6 <- grep("endometrium_6", colnames(count_data_b))
count_data_endometrium_6 <- count_data_b[, endometrium_columns_6]
```

```{r}
count_data_endometrium_6$geneID <- rownames(count_data_endometrium_6)
```

```{r}
endometrium_6_count_data_annotated<-merge(count_data_endometrium_6,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_endometrium_6 <- count_data_endometrium_6[, -ncol(count_data_endometrium_6)]

endometrium_6_gene_length<-endometrium_6_count_data_annotated$transcript_length
```

```{r}
x <- count_data_endometrium_6 / endometrium_6_gene_length
endometrium_6_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
endometrium_6_fpkm<-as.data.frame(edgeR::rpkm(count_data_endometrium_6, endometrium_6_gene_length))
endometrium_6_cpm<-as.data.frame(edgeR::cpm(count_data_endometrium_6))
endometrium_6_cpm_filtered<-endometrium_6_cpm[rowSums(endometrium_6_cpm>1) > 9,]
endometrium_6_tpm_filtered<-endometrium_6_fpkm[rowSums(endometrium_6_tpm>1) > 9,]

genes_expressed_endometrium_6<-intersect(rownames(endometrium_6_cpm_filtered), rownames(endometrium_6_tpm_filtered))

endometrium_6_tpm_filtered<-endometrium_6_tpm_filtered[rownames(endometrium_6_tpm_filtered) %in% genes_expressed_endometrium_6,]
endometrium_6_cpm_filtered<-endometrium_6_cpm_filtered[rownames(endometrium_6_cpm_filtered) %in% genes_expressed_endometrium_6,]

endometrium_6_count_filtered<-count_data_endometrium_6[rownames(count_data_endometrium_6) %in% genes_expressed_endometrium_6,]

endometrium_6_tpm_filtered<-endometrium_6_tpm_filtered[complete.cases(endometrium_6_tpm_filtered),]
endometrium_6_count_filtered<-endometrium_6_count_filtered[complete.cases(endometrium_6_count_filtered),]

```

```{r}
write_delim(endometrium_6_count_filtered,
            "/home/yassine/Downloads/between_tissue/endometrium_6_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(endometrium_6_count_filtered)
norm_factors <- calcNormFactors(object = endometrium_6_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_endometrium_6 <- sweep(endometrium_6_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_endometrium_6<-asinh(CTF_normalized_endometrium_6)
```


```{r}
write_delim(asinh_transf_CTF_normalized_endometrium_6,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_endometrium_6.txt",
            delim = "\t",
            quote =  "none")
```



```{r}
endometrium_columns_9<- grep("endometrium_9", colnames(count_data_b))
count_data_endometrium_9<- count_data_b[, endometrium_columns_9]
```

```{r}
count_data_endometrium_9$geneID <- rownames(count_data_endometrium_9)
```

```{r}
endometrium_9_count_data_annotated<-merge(count_data_endometrium_9,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_endometrium_9<- count_data_endometrium_9[, -ncol(count_data_endometrium_9)]

endometrium_9_gene_length<-endometrium_9_count_data_annotated$transcript_length
```

```{r}
x <- count_data_endometrium_9/ endometrium_9_gene_length
endometrium_9_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
endometrium_9_fpkm<-as.data.frame(edgeR::rpkm(count_data_endometrium_9, endometrium_9_gene_length))
endometrium_9_cpm<-as.data.frame(edgeR::cpm(count_data_endometrium_9))
endometrium_9_cpm_filtered<-endometrium_9_cpm[rowSums(endometrium_9_cpm>1) > 9,]
endometrium_9_tpm_filtered<-endometrium_9_fpkm[rowSums(endometrium_9_tpm>1) > 9,]

genes_expressed_endometrium_9<-intersect(rownames(endometrium_9_cpm_filtered), rownames(endometrium_9_tpm_filtered))

endometrium_9_tpm_filtered<-endometrium_9_tpm_filtered[rownames(endometrium_9_tpm_filtered) %in% genes_expressed_endometrium_9,]
endometrium_9_cpm_filtered<-endometrium_9_cpm_filtered[rownames(endometrium_9_cpm_filtered) %in% genes_expressed_endometrium_9,]

endometrium_9_count_filtered<-count_data_endometrium_9[rownames(count_data_endometrium_9) %in% genes_expressed_endometrium_9,]

endometrium_9_tpm_filtered<-endometrium_9_tpm_filtered[complete.cases(endometrium_9_tpm_filtered),]
endometrium_9_count_filtered<-endometrium_9_count_filtered[complete.cases(endometrium_9_count_filtered),]

```

```{r}
write_delim(endometrium_9_count_filtered,
            "/home/yassine/Downloads/between_tissue/endometrium_9_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(endometrium_9_count_filtered)
norm_factors <- calcNormFactors(object = endometrium_9_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_endometrium_9 <- sweep(endometrium_9_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_endometrium_9<-asinh(CTF_normalized_endometrium_9)
```


```{r}
write_delim(asinh_transf_CTF_normalized_endometrium_9,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_endometrium_9.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
endometrium_columns_19<- grep("endometrium_19", colnames(count_data_b))
count_data_endometrium_19<- count_data_b[, endometrium_columns_19]
```

```{r}
count_data_endometrium_19$geneID <- rownames(count_data_endometrium_19)
```

```{r}
endometrium_19_count_data_annotated<-merge(count_data_endometrium_19,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_endometrium_19<- count_data_endometrium_19[, -ncol(count_data_endometrium_19)]

endometrium_19_gene_length<-endometrium_19_count_data_annotated$transcript_length
```

```{r}
x <- count_data_endometrium_19/ endometrium_19_gene_length
endometrium_19_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
endometrium_19_fpkm<-as.data.frame(edgeR::rpkm(count_data_endometrium_19, endometrium_19_gene_length))
endometrium_19_cpm<-as.data.frame(edgeR::cpm(count_data_endometrium_19))
endometrium_19_cpm_filtered<-endometrium_19_cpm[rowSums(endometrium_19_cpm>1) > 9,]
endometrium_19_tpm_filtered<-endometrium_19_fpkm[rowSums(endometrium_19_tpm>1) > 9,]

genes_expressed_endometrium_19<-intersect(rownames(endometrium_19_cpm_filtered), rownames(endometrium_19_tpm_filtered))

endometrium_19_tpm_filtered<-endometrium_19_tpm_filtered[rownames(endometrium_19_tpm_filtered) %in% genes_expressed_endometrium_19,]
endometrium_19_cpm_filtered<-endometrium_19_cpm_filtered[rownames(endometrium_19_cpm_filtered) %in% genes_expressed_endometrium_19,]

endometrium_19_count_filtered<-count_data_endometrium_19[rownames(count_data_endometrium_19) %in% genes_expressed_endometrium_19,]

endometrium_19_tpm_filtered<-endometrium_19_tpm_filtered[complete.cases(endometrium_19_tpm_filtered),]
endometrium_19_count_filtered<-endometrium_19_count_filtered[complete.cases(endometrium_19_count_filtered),]

```

```{r}
write_delim(endometrium_19_count_filtered,
            "/home/yassine/Downloads/between_tissue/endometrium_19_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(endometrium_19_count_filtered)
norm_factors <- calcNormFactors(object = endometrium_19_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_endometrium_19 <- sweep(endometrium_19_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_endometrium_19<-asinh(CTF_normalized_endometrium_19)
```


```{r}
write_delim(asinh_transf_CTF_normalized_endometrium_19,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_endometrium_19.txt",
            delim = "\t",
            quote =  "none")
```


#-----------------


```{r}
hypothalamus_columns_6 <- grep("hypothalamus_6", colnames(count_data_b))
count_data_hypothalamus_6 <- count_data_b[, hypothalamus_columns_6]
```

```{r}
count_data_hypothalamus_6$geneID <- rownames(count_data_hypothalamus_6)
```

```{r}
hypothalamus_6_count_data_annotated<-merge(count_data_hypothalamus_6,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_hypothalamus_6 <- count_data_hypothalamus_6[, -ncol(count_data_hypothalamus_6)]

hypothalamus_6_gene_length<-hypothalamus_6_count_data_annotated$transcript_length
```

```{r}
x <- count_data_hypothalamus_6 / hypothalamus_6_gene_length
hypothalamus_6_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
hypothalamus_6_fpkm<-as.data.frame(edgeR::rpkm(count_data_hypothalamus_6, hypothalamus_6_gene_length))
hypothalamus_6_cpm<-as.data.frame(edgeR::cpm(count_data_hypothalamus_6))
hypothalamus_6_cpm_filtered<-hypothalamus_6_cpm[rowSums(hypothalamus_6_cpm>1) > 9,]
hypothalamus_6_tpm_filtered<-hypothalamus_6_fpkm[rowSums(hypothalamus_6_tpm>1) > 9,]

genes_expressed_hypothalamus_6<-intersect(rownames(hypothalamus_6_cpm_filtered), rownames(hypothalamus_6_tpm_filtered))

hypothalamus_6_tpm_filtered<-hypothalamus_6_tpm_filtered[rownames(hypothalamus_6_tpm_filtered) %in% genes_expressed_hypothalamus_6,]
hypothalamus_6_cpm_filtered<-hypothalamus_6_cpm_filtered[rownames(hypothalamus_6_cpm_filtered) %in% genes_expressed_hypothalamus_6,]

hypothalamus_6_count_filtered<-count_data_hypothalamus_6[rownames(count_data_hypothalamus_6) %in% genes_expressed_hypothalamus_6,]

hypothalamus_6_tpm_filtered<-hypothalamus_6_tpm_filtered[complete.cases(hypothalamus_6_tpm_filtered),]
hypothalamus_6_count_filtered<-hypothalamus_6_count_filtered[complete.cases(hypothalamus_6_count_filtered),]

```

```{r}
write_delim(hypothalamus_6_count_filtered,
            "/home/yassine/Downloads/between_tissue/hypothalamus_6_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(hypothalamus_6_count_filtered)
norm_factors <- calcNormFactors(object = hypothalamus_6_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_hypothalamus_6 <- sweep(hypothalamus_6_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_hypothalamus_6<-asinh(CTF_normalized_hypothalamus_6)
```


```{r}
write_delim(asinh_transf_CTF_normalized_hypothalamus_6,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_hypothalamus_6.txt",
            delim = "\t",
            quote =  "none")
```



```{r}
hypothalamus_columns_9<- grep("hypothalamus_9", colnames(count_data_b))
count_data_hypothalamus_9<- count_data_b[, hypothalamus_columns_9]
```

```{r}
count_data_hypothalamus_9$geneID <- rownames(count_data_hypothalamus_9)
```

```{r}
hypothalamus_9_count_data_annotated<-merge(count_data_hypothalamus_9,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_hypothalamus_9<- count_data_hypothalamus_9[, -ncol(count_data_hypothalamus_9)]

hypothalamus_9_gene_length<-hypothalamus_9_count_data_annotated$transcript_length
```

```{r}
x <- count_data_hypothalamus_9/ hypothalamus_9_gene_length
hypothalamus_9_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
hypothalamus_9_fpkm<-as.data.frame(edgeR::rpkm(count_data_hypothalamus_9, hypothalamus_9_gene_length))
hypothalamus_9_cpm<-as.data.frame(edgeR::cpm(count_data_hypothalamus_9))
hypothalamus_9_cpm_filtered<-hypothalamus_9_cpm[rowSums(hypothalamus_9_cpm>1) > 9,]
hypothalamus_9_tpm_filtered<-hypothalamus_9_fpkm[rowSums(hypothalamus_9_tpm>1) > 9,]

genes_expressed_hypothalamus_9<-intersect(rownames(hypothalamus_9_cpm_filtered), rownames(hypothalamus_9_tpm_filtered))

hypothalamus_9_tpm_filtered<-hypothalamus_9_tpm_filtered[rownames(hypothalamus_9_tpm_filtered) %in% genes_expressed_hypothalamus_9,]
hypothalamus_9_cpm_filtered<-hypothalamus_9_cpm_filtered[rownames(hypothalamus_9_cpm_filtered) %in% genes_expressed_hypothalamus_9,]

hypothalamus_9_count_filtered<-count_data_hypothalamus_9[rownames(count_data_hypothalamus_9) %in% genes_expressed_hypothalamus_9,]

hypothalamus_9_tpm_filtered<-hypothalamus_9_tpm_filtered[complete.cases(hypothalamus_9_tpm_filtered),]
hypothalamus_9_count_filtered<-hypothalamus_9_count_filtered[complete.cases(hypothalamus_9_count_filtered),]

```

```{r}
write_delim(hypothalamus_9_count_filtered,
            "/home/yassine/Downloads/between_tissue/hypothalamus_9_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(hypothalamus_9_count_filtered)
norm_factors <- calcNormFactors(object = hypothalamus_9_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_hypothalamus_9 <- sweep(hypothalamus_9_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_hypothalamus_9<-asinh(CTF_normalized_hypothalamus_9)
```


```{r}
write_delim(asinh_transf_CTF_normalized_hypothalamus_9,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_hypothalamus_9.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
hypothalamus_columns_19<- grep("hypothalamus_19", colnames(count_data_b))
count_data_hypothalamus_19<- count_data_b[, hypothalamus_columns_19]
```

```{r}
count_data_hypothalamus_19$geneID <- rownames(count_data_hypothalamus_19)
```

```{r}
hypothalamus_19_count_data_annotated<-merge(count_data_hypothalamus_19,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_hypothalamus_19<- count_data_hypothalamus_19[, -ncol(count_data_hypothalamus_19)]

hypothalamus_19_gene_length<-hypothalamus_19_count_data_annotated$transcript_length
```

```{r}
x <- count_data_hypothalamus_19/ hypothalamus_19_gene_length
hypothalamus_19_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
hypothalamus_19_fpkm<-as.data.frame(edgeR::rpkm(count_data_hypothalamus_19, hypothalamus_19_gene_length))
hypothalamus_19_cpm<-as.data.frame(edgeR::cpm(count_data_hypothalamus_19))
hypothalamus_19_cpm_filtered<-hypothalamus_19_cpm[rowSums(hypothalamus_19_cpm>1) > 9,]
hypothalamus_19_tpm_filtered<-hypothalamus_19_fpkm[rowSums(hypothalamus_19_tpm>1) > 9,]

genes_expressed_hypothalamus_19<-intersect(rownames(hypothalamus_19_cpm_filtered), rownames(hypothalamus_19_tpm_filtered))

hypothalamus_19_tpm_filtered<-hypothalamus_19_tpm_filtered[rownames(hypothalamus_19_tpm_filtered) %in% genes_expressed_hypothalamus_19,]
hypothalamus_19_cpm_filtered<-hypothalamus_19_cpm_filtered[rownames(hypothalamus_19_cpm_filtered) %in% genes_expressed_hypothalamus_19,]

hypothalamus_19_count_filtered<-count_data_hypothalamus_19[rownames(count_data_hypothalamus_19) %in% genes_expressed_hypothalamus_19,]

hypothalamus_19_tpm_filtered<-hypothalamus_19_tpm_filtered[complete.cases(hypothalamus_19_tpm_filtered),]
hypothalamus_19_count_filtered<-hypothalamus_19_count_filtered[complete.cases(hypothalamus_19_count_filtered),]

```

```{r}
write_delim(hypothalamus_19_count_filtered,
            "/home/yassine/Downloads/between_tissue/hypothalamus_19_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(hypothalamus_19_count_filtered)
norm_factors <- calcNormFactors(object = hypothalamus_19_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_hypothalamus_19 <- sweep(hypothalamus_19_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_hypothalamus_19<-asinh(CTF_normalized_hypothalamus_19)
```


```{r}
write_delim(asinh_transf_CTF_normalized_hypothalamus_19,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_hypothalamus_19.txt",
            delim = "\t",
            quote =  "none")
```

#-------------------


```{r}
pituitary_columns_6 <- grep("pituitary_6", colnames(count_data_b))
count_data_pituitary_6 <- count_data_b[, pituitary_columns_6]
```

```{r}
count_data_pituitary_6$geneID <- rownames(count_data_pituitary_6)
```

```{r}
pituitary_6_count_data_annotated<-merge(count_data_pituitary_6,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_pituitary_6 <- count_data_pituitary_6[, -ncol(count_data_pituitary_6)]

pituitary_6_gene_length<-pituitary_6_count_data_annotated$transcript_length
```

```{r}
x <- count_data_pituitary_6 / pituitary_6_gene_length
pituitary_6_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
pituitary_6_fpkm<-as.data.frame(edgeR::rpkm(count_data_pituitary_6, pituitary_6_gene_length))
pituitary_6_cpm<-as.data.frame(edgeR::cpm(count_data_pituitary_6))
pituitary_6_cpm_filtered<-pituitary_6_cpm[rowSums(pituitary_6_cpm>1) > 9,]
pituitary_6_tpm_filtered<-pituitary_6_fpkm[rowSums(pituitary_6_tpm>1) > 9,]

genes_expressed_pituitary_6<-intersect(rownames(pituitary_6_cpm_filtered), rownames(pituitary_6_tpm_filtered))

pituitary_6_tpm_filtered<-pituitary_6_tpm_filtered[rownames(pituitary_6_tpm_filtered) %in% genes_expressed_pituitary_6,]
pituitary_6_cpm_filtered<-pituitary_6_cpm_filtered[rownames(pituitary_6_cpm_filtered) %in% genes_expressed_pituitary_6,]

pituitary_6_count_filtered<-count_data_pituitary_6[rownames(count_data_pituitary_6) %in% genes_expressed_pituitary_6,]

pituitary_6_tpm_filtered<-pituitary_6_tpm_filtered[complete.cases(pituitary_6_tpm_filtered),]
pituitary_6_count_filtered<-pituitary_6_count_filtered[complete.cases(pituitary_6_count_filtered),]

```

```{r}
write_delim(pituitary_6_count_filtered,
            "/home/yassine/Downloads/between_tissue/pituitary_6_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(pituitary_6_count_filtered)
norm_factors <- calcNormFactors(object = pituitary_6_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_pituitary_6 <- sweep(pituitary_6_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_pituitary_6<-asinh(CTF_normalized_pituitary_6)
```


```{r}
write_delim(asinh_transf_CTF_normalized_pituitary_6,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_pituitary_6.txt",
            delim = "\t",
            quote =  "none")
```



```{r}
pituitary_columns_9<- grep("pituitary_9", colnames(count_data_b))
count_data_pituitary_9<- count_data_b[, pituitary_columns_9]
```

```{r}
count_data_pituitary_9$geneID <- rownames(count_data_pituitary_9)
```

```{r}
pituitary_9_count_data_annotated<-merge(count_data_pituitary_9,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_pituitary_9<- count_data_pituitary_9[, -ncol(count_data_pituitary_9)]

pituitary_9_gene_length<-pituitary_9_count_data_annotated$transcript_length
```

```{r}
x <- count_data_pituitary_9/ pituitary_9_gene_length
pituitary_9_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
pituitary_9_fpkm<-as.data.frame(edgeR::rpkm(count_data_pituitary_9, pituitary_9_gene_length))
pituitary_9_cpm<-as.data.frame(edgeR::cpm(count_data_pituitary_9))
pituitary_9_cpm_filtered<-pituitary_9_cpm[rowSums(pituitary_9_cpm>1) > 9,]
pituitary_9_tpm_filtered<-pituitary_9_fpkm[rowSums(pituitary_9_tpm>1) > 9,]

genes_expressed_pituitary_9<-intersect(rownames(pituitary_9_cpm_filtered), rownames(pituitary_9_tpm_filtered))

pituitary_9_tpm_filtered<-pituitary_9_tpm_filtered[rownames(pituitary_9_tpm_filtered) %in% genes_expressed_pituitary_9,]
pituitary_9_cpm_filtered<-pituitary_9_cpm_filtered[rownames(pituitary_9_cpm_filtered) %in% genes_expressed_pituitary_9,]

pituitary_9_count_filtered<-count_data_pituitary_9[rownames(count_data_pituitary_9) %in% genes_expressed_pituitary_9,]

pituitary_9_tpm_filtered<-pituitary_9_tpm_filtered[complete.cases(pituitary_9_tpm_filtered),]
pituitary_9_count_filtered<-pituitary_9_count_filtered[complete.cases(pituitary_9_count_filtered),]

```

```{r}
write_delim(pituitary_9_count_filtered,
            "/home/yassine/Downloads/between_tissue/pituitary_9_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(pituitary_9_count_filtered)
norm_factors <- calcNormFactors(object = pituitary_9_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_pituitary_9 <- sweep(pituitary_9_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_pituitary_9<-asinh(CTF_normalized_pituitary_9)
```


```{r}
write_delim(asinh_transf_CTF_normalized_pituitary_9,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_pituitary_9.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
pituitary_columns_19<- grep("pituitary_19", colnames(count_data_b))
count_data_pituitary_19<- count_data_b[, pituitary_columns_19]
```

```{r}
count_data_pituitary_19$geneID <- rownames(count_data_pituitary_19)
```

```{r}
pituitary_19_count_data_annotated<-merge(count_data_pituitary_19,
                                   annotation.ensembl.symbol,
                                   by.x="geneID",
                                   by.y="ensembl_gene_id",
                                   all.x=FALSE, 
                                   all.y=FALSE)
count_data_pituitary_19<- count_data_pituitary_19[, -ncol(count_data_pituitary_19)]

pituitary_19_gene_length<-pituitary_19_count_data_annotated$transcript_length
```

```{r}
x <- count_data_pituitary_19/ pituitary_19_gene_length
pituitary_19_tpm <- as.data.frame(t( t(x) * 1e6 / colSums(x) ))
pituitary_19_fpkm<-as.data.frame(edgeR::rpkm(count_data_pituitary_19, pituitary_19_gene_length))
pituitary_19_cpm<-as.data.frame(edgeR::cpm(count_data_pituitary_19))
pituitary_19_cpm_filtered<-pituitary_19_cpm[rowSums(pituitary_19_cpm>1) > 9,]
pituitary_19_tpm_filtered<-pituitary_19_fpkm[rowSums(pituitary_19_tpm>1) > 9,]

genes_expressed_pituitary_19<-intersect(rownames(pituitary_19_cpm_filtered), rownames(pituitary_19_tpm_filtered))

pituitary_19_tpm_filtered<-pituitary_19_tpm_filtered[rownames(pituitary_19_tpm_filtered) %in% genes_expressed_pituitary_19,]
pituitary_19_cpm_filtered<-pituitary_19_cpm_filtered[rownames(pituitary_19_cpm_filtered) %in% genes_expressed_pituitary_19,]

pituitary_19_count_filtered<-count_data_pituitary_19[rownames(count_data_pituitary_19) %in% genes_expressed_pituitary_19,]

pituitary_19_tpm_filtered<-pituitary_19_tpm_filtered[complete.cases(pituitary_19_tpm_filtered),]
pituitary_19_count_filtered<-pituitary_19_count_filtered[complete.cases(pituitary_19_count_filtered),]

```

```{r}
write_delim(pituitary_19_count_filtered,
            "/home/yassine/Downloads/between_tissue/pituitary_19_count_filtered.txt",
            delim = "\t",
            quote =  "none")
```


```{r}
# CTF and asinh transform the filtered  read count data
lib_size <- base::colSums(pituitary_19_count_filtered)
norm_factors <- calcNormFactors(object = pituitary_19_count_filtered,
                                lib.size = lib_size,
                                method = "TMM")
CTF_normalized_pituitary_19 <- sweep(pituitary_19_count_filtered,2,norm_factors,"/")
asinh_transf_CTF_normalized_pituitary_19<-asinh(CTF_normalized_pituitary_19)
```


```{r}
write_delim(asinh_transf_CTF_normalized_pituitary_19,
            "/home/yassine/Downloads/between_tissue/asinh_transf_CTF_normalized_pituitary_19.txt",
            delim = "\t",
            quote =  "none")
```
